### ISSUE TITLE
Segfault when resizing window with populated TableView

### ISSUE THREAD

**Issue by Phrogz** [ryanmelt/qtbindings#101]
The below program is in a single file. It has a `MainWindow` filled with a `Qt::TableView` populated with 4 rows and two columns. When I launch the app it works. When I grab the resize handle for the window and resize repeatedly (move the mouse in circles while resizing) the app segfaults within 1-2 seconds.

Thank you for any help you can provide in tracking this down and squashing it. In general this is making development on my app stalled, since many resize interactions with the real app result in a segfault. Hopefully I'm not doing something dumb in my AbstractItemModel.

* OS X 10.10 (I have had similar crashes on Win7x64, but _this_ test case does not repro)
* ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin13.3.0]
* Qt 4.8.6
* qtbindings 4.8.5.2

```
/Users/phrogz/.rvm/gems/ruby-2.0.0-p353/gems/qtbindings-4.8.5.2/lib/Qt/qtruby4.rb:479: [BUG] Segmentation fault
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin13.3.0]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0011 e:000010 CFUNC  :method_missing
c:0003 p:0009 s:0007 e:000006 METHOD /Users/phrogz/.rvm/gems/ruby-2.0.0-p353/gems/qtbindings-4.8.5.2/lib/Qt/qtruby4.rb:479
c:0002 p:0096 s:0004 E:001ee8 EVAL   launch.rb:131 [FINISH]
c:0001 p:0000 s:0002 E:0012f8 TOP    [FINISH]

launch.rb:131:in `<main>'
/Users/phrogz/.rvm/gems/ruby-2.0.0-p353/gems/qtbindings-4.8.5.2/lib/Qt/qtruby4.rb:479:in `exec'
/Users/phrogz/.rvm/gems/ruby-2.0.0-p353/gems/qtbindings-4.8.5.2/lib/Qt/qtruby4.rb:479:in `method_missing'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: launch.rb

* Loaded features:

    0 enumerator.so
    1 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/x86_64-darwin13.3.0/enc/encdb.bundle
    2 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/x86_64-darwin13.3.0/enc/trans/transdb.bundle
    3 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/x86_64-darwin13.3.0/rbconfig.rb
    4 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/compatibility.rb
    5 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/defaults.rb
    6 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/deprecate.rb
    7 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/errors.rb
    8 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/version.rb
    9 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/requirement.rb
   10 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/platform.rb
   11 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/basic_specification.rb
   12 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/stub_specification.rb
   13 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/util/stringio.rb
   14 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb
   15 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/exceptions.rb
   16 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
   17 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/thread.rb
   18 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/monitor.rb
   19 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb
   20 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems.rb
   21 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/path_support.rb
   22 /Users/phrogz/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/dependency.rb
   23 /Users/phrogz/.rvm/gems/ruby-2.0.0-p353/gems/qtbindings-4.8.5.2/lib/Qt/qtruby4.rb
   24 /Users/phrogz/.rvm/gems/ruby-2.0.0-p353/gems/qtbindings-4.8.5.2/lib/2.0/qtruby4.bundle
   25 /Users/phrogz/.rvm/gems/ruby-2.0.0-p353/gems/qtbindings-4.8.5.2/lib/Qt4.rb
   26 /Users/phrogz/.rvm/gems/ruby-2.0.0-p353/gems/qtbindings-4.8.5.2/lib/Qt.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
```

``` ruby
require 'Qt'

class MyWin < Qt::MainWindow
  def initialize(parent=nil, &block)
    super(parent)
    @ui = Ui_MainWin.new
    @ui.setupUi(self)
    @ui.inspector.model = AttributesModel.new(self)
  end
end

class AttributesModel < Qt::AbstractItemModel
  INVALIDINDEX = Qt::ModelIndex.new
  NODATA       = Qt::Variant.new
  def initialize(qtparent)
    super(qtparent)
    @indexes = {} # indexed by [row,col]
    @root   = Qt::ModelIndex.new
    values = [
      {name:'Background',value:'blue'},
      {name:'End Time',value:'10000'},
      {name:'Name',value:'Some Name'},
      {name:'Start Time',value:'0'},
    ]
    values.each.with_index do |value,i|
      @indexes[[i,0]] = createIndex( i, 0, Qt::Variant.new(value[:name] ) )
      @indexes[[i,1]] = createIndex( i, 1, Qt::Variant.new(value[:value]) )
    end
  end

  def columnCount( *any )
    2
  end

  def index( row, col, parent=INVALIDINDEX )
    @indexes[[row,col]] || INVALIDINDEX
  end

  def headerData(section, orientation, role=Qt::DisplayRole)
    if orientation==Qt::Horizontal && role==Qt::DisplayRole
      case section
        when 0; Qt::Variant.new(tr("Attribute"))
        when 1; Qt::Variant.new(tr("Value"))
        else  ; NODATA
      end
    else
      NODATA
    end
  end

  def parent(child)
    child.valid? ? @root : INVALIDINDEX
  end

  def rowCount( parent=INVALIDINDEX )
    @rowcount ||= @indexes.length
  end

  def data(index, role)
    if index.valid? && role == Qt::DisplayRole
      index.internal_pointer
    else
      NODATA
    end
  end
end

class Ui_MainWin # Generated by rbuic4
    attr_reader :centralwidget
    attr_reader :horizontalLayout
    attr_reader :inspector
    attr_reader :statusbar

    def setupUi(mainWin)
    if mainWin.objectName.nil?
        mainWin.objectName = "mainWin"
    end
    mainWin.resize(600, 400)
    mainWin.styleSheet = "QPlainTextEdit, QTableView, QTreeView { border:1px solid #898c95 }"
    mainWin.unifiedTitleAndToolBarOnMac = false
    @centralwidget = Qt::Widget.new(mainWin)
    @centralwidget.objectName = "centralwidget"
    @sizePolicy = Qt::SizePolicy.new(Qt::SizePolicy::Preferred, Qt::SizePolicy::Minimum)
    @sizePolicy.setHorizontalStretch(0)
    @sizePolicy.setVerticalStretch(0)
    @sizePolicy.heightForWidth = @centralwidget.sizePolicy.hasHeightForWidth
    @centralwidget.sizePolicy = @sizePolicy
    @centralwidget.autoFillBackground = true
    @horizontalLayout = Qt::HBoxLayout.new(@centralwidget)
    @horizontalLayout.objectName = "horizontalLayout"
    @inspector = Qt::TableView.new(@centralwidget)
    @inspector.objectName = "inspector"
    @inspector.minimumSize = Qt::Size.new(0, 60)
    @font = Qt::Font.new
    @font.pointSize = 12
    @inspector.font = @font
    @inspector.styleSheet = ""
    @inspector.horizontalScrollBarPolicy = Qt::ScrollBarAlwaysOff
    @inspector.showGrid = false
    @inspector.gridStyle = Qt::NoPen
    @inspector.wordWrap = false

    @horizontalLayout.addWidget(@inspector)

    mainWin.centralWidget = @centralwidget
    @statusbar = Qt::StatusBar.new(mainWin)
    @statusbar.objectName = "statusbar"
    mainWin.statusBar = @statusbar

    retranslateUi(mainWin)

    Qt::MetaObject.connectSlotsByName(mainWin)
    end # setupUi

    def setup_ui(mainWin)
        setupUi(mainWin)
    end

    def retranslateUi(mainWin)
    mainWin.windowTitle = Qt::Application.translate("MainWin", "UIC Inspectamator", nil, Qt::Application::UnicodeUTF8)
    end # retranslateUi

    def retranslate_ui(mainWin)
        retranslateUi(mainWin)
    end
end

$app = Qt::Application.new(ARGV)
MyWin.new.show
$app.exec
```

**Comment by ryanatball** [comment]
Sorry, but I don't know enough about AbstractItemModel, etc to help with this one.   There are working examples that derive from AbstractItemModel included with qtbindings.  I would look at those for reference.  examples/itemviews/simpledommodel for example.
