### ISSUE TITLE
rbuic4 doesn't work bc it can't find shared library

### ISSUE THREAD

**Issue by Lykos** [ryanmelt/qtbindings#164]
I am getting the following error:

$ rbuic4
Traceback (most recent call last):
	10: from /usr/local/bin/rbuic4:23:in `<main>'
	 9: from /usr/local/bin/rbuic4:23:in `load'
	 8: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/bin/rbuic4:4:in `<top (required)>'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt.rb:1:in `<top (required)>'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 2: from /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt4.rb:25:in `<top (required)>'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': libqtruby4shared.so.2: cannot open shared object file: No such file or directory - /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/2.5/qtruby4.so (LoadError)

I am using Ubuntu and I have qt4 installed. The interesting thing is that the file that this error is talking about actually seems to exist:

$ ls /var/lib/gems/2.5.0/gems/qtbindings-4.8.6.5/lib/2.5/
libqtruby4shared.so        libsmokeqtdbus.so.3.0.0         libsmokeqtnetwork.so.3      libsmokeqtsvg.so            libsmokeqtxmlpatterns.so.3.0.0
libqtruby4shared.so.2      libsmokeqtdeclarative.so        libsmokeqtnetwork.so.3.0.0  libsmokeqtsvg.so.3          libsmokeqtxml.so
libqtruby4shared.so.2.0.0  libsmokeqtdeclarative.so.3      libsmokeqtopengl.so         libsmokeqtsvg.so.3.0.0      libsmokeqtxml.so.3
libsmokebase.so            libsmokeqtdeclarative.so.3.0.0  libsmokeqtopengl.so.3       libsmokeqttest.so           libsmokeqtxml.so.3.0.0
libsmokebase.so.3          libsmokeqtgui.so                libsmokeqtopengl.so.3.0.0   libsmokeqttest.so.3         qtdeclarative.so
libsmokebase.so.3.0.0      libsmokeqtgui.so.3              libsmokeqtscript.so         libsmokeqttest.so.3.0.0     qtruby4.so
libsmokeqtcore.so          libsmokeqtgui.so.3.0.0          libsmokeqtscript.so.3       libsmokeqtuitools.so        qtscript.so
libsmokeqtcore.so.3        libsmokeqthelp.so               libsmokeqtscript.so.3.0.0   libsmokeqtuitools.so.3      qttest.so
libsmokeqtcore.so.3.0.0    libsmokeqthelp.so.3             libsmokeqtsql.so            libsmokeqtuitools.so.3.0.0  qtuitools.so
libsmokeqtdbus.so          libsmokeqthelp.so.3.0.0         libsmokeqtsql.so.3          libsmokeqtxmlpatterns.so
libsmokeqtdbus.so.3        libsmokeqtnetwork.so            libsmokeqtsql.so.3.0.0      libsmokeqtxmlpatterns.so.3

**Comment by Lykos** [comment]
Idk what happened, but it went away now. I did several attempts, but never got this to disappear. I reinstalled packages, restarted, tried to follow some internet descriptions for people with similar errors (mostly they told me to use ldconfig) and nothing worked.

And now, one day, it just worked. But I am closing this now as it is probably not reproducible and I don't know whether it is connected to this gem or just to the state of my system. But if others have this, feel free to reopen.
