### ISSUE TITLE
Segfault running flowlayout example

### ISSUE THREAD

**Issue by Phrogz** [ryanmelt/qtbindings#98]
```
C:\Ruby\lib\ruby\gems\2.0.0\gems\qtbindings-4.8.6.0-x86-mingw32\examples\layouts\flowlayouts>ruby -v
ruby 2.0.0p576 (2014-09-19) [i386-mingw32]

C:\Ruby\lib\ruby\gems\2.0.0\gems\qtbindings-4.8.6.0-x86-mingw32\examples\layouts\flowlayouts>ruby main.rb
C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt/qtruby4.rb:479: [BUG] Segmentation fault
ruby 2.0.0p576 (2014-09-19) [i386-mingw32]

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0014 e:000013 CFUNC  :method_missing
c:0003 p:0009 s:0010 e:000009 METHOD C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt/qtruby4.rb:479
c:0002 p:0064 s:0006 E:001f34 EVAL   main.rb:32 [FINISH]
c:0001 p:0000 s:0002 E:00242c TOP    [FINISH]

main.rb:32:in `<main>'
C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt/qtruby4.rb:479:in `exec'
C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt/qtruby4.rb:479:in `method_missing'

-- C level backtrace information -------------------------------------------
C:\Windows\SysWOW64\ntdll.dll(ZwWaitForSingleObject+0x15) [0x777FF861]
C:\Windows\syswow64\kernel32.dll(WaitForSingleObjectEx+0x43) [0x74F51184]
C:\Windows\syswow64\kernel32.dll(WaitForSingleObject+0x12) [0x74F51138]
C:\Ruby\bin\msvcrt-ruby200.dll(rb_vm_bugreport+0xa7) [0x66903267]
C:\Ruby\bin\msvcrt-ruby200.dll(rb_name_err_mesg_new+0x69d) [0x667C18DD]
C:\Ruby\bin\msvcrt-ruby200.dll(rb_bug+0x2e) [0x667C26FE]
C:\Ruby\bin\msvcrt-ruby200.dll(rb_check_safe_str+0x39a) [0x6688666A]
 [0x00401866]
C:\Windows\SysWOW64\ntdll.dll(RtlKnownExceptionFilter+0xb7) [0x778506E7]

-- Other runtime information -----------------------------------------------

* Loaded script: main.rb

* Loaded features:

    0 enumerator.so
    1 C:/Ruby/lib/ruby/2.0.0/i386-mingw32/enc/encdb.so
    2 C:/Ruby/lib/ruby/2.0.0/i386-mingw32/enc/iso_8859_1.so
    3 C:/Ruby/lib/ruby/2.0.0/i386-mingw32/enc/trans/transdb.so
    4 C:/Ruby/lib/ruby/2.0.0/i386-mingw32/rbconfig.rb
    5 C:/Ruby/lib/ruby/2.0.0/rubygems/compatibility.rb
    6 C:/Ruby/lib/ruby/2.0.0/rubygems/defaults.rb
    7 C:/Ruby/lib/ruby/2.0.0/rubygems/deprecate.rb
    8 C:/Ruby/lib/ruby/2.0.0/rubygems/errors.rb
    9 C:/Ruby/lib/ruby/2.0.0/rubygems/version.rb
   10 C:/Ruby/lib/ruby/2.0.0/rubygems/requirement.rb
   11 C:/Ruby/lib/ruby/2.0.0/rubygems/platform.rb
   12 C:/Ruby/lib/ruby/2.0.0/rubygems/specification.rb
   13 C:/Ruby/lib/ruby/2.0.0/rubygems/exceptions.rb
   14 C:/Ruby/lib/ruby/2.0.0/rubygems/defaults/operating_system.rb
   15 C:/Ruby/lib/ruby/2.0.0/i386-mingw32/enc/utf_16le.so
   16 C:/Ruby/lib/ruby/2.0.0/i386-mingw32/enc/trans/utf_16_32.so
   17 C:/Ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
   18 C:/Ruby/lib/ruby/2.0.0/thread.rb
   19 C:/Ruby/lib/ruby/2.0.0/monitor.rb
   20 C:/Ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
   21 C:/Ruby/lib/ruby/2.0.0/rubygems.rb
   22 C:/Ruby/lib/ruby/2.0.0/rubygems/path_support.rb
   23 C:/Ruby/lib/ruby/2.0.0/rubygems/dependency.rb
   24 C:/Ruby/lib/ruby/2.0.0/i386-mingw32/enc/trans/single_byte.so
   25 C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-qt-4.8.6-x86-mingw32/qtlib/qtbindings-qt.rb
   26 C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt/qtruby4.rb
   27 C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/2.0/qtruby4.so
   28 C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt4.rb
   29 C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-4.8.6.0-x86-mingw32/lib/Qt.rb
   30 C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-4.8.6.0-x86-mingw32/examples/layouts/flowlayouts/flowlayout.rb
   31 C:/Ruby/lib/ruby/gems/2.0.0/gems/qtbindings-4.8.6.0-x86-mingw32/examples/layouts/flowlayouts/window.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html


This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by jmthomas** [comment]
This code has now been open sourced here: https://github.com/BallAerospace/COSMOS/blob/master/lib/cosmos/gui/qt.rb
